### PR TITLE
Add collaborations section

### LINKED ISSUE #76: Describe collaborations
We should only include public projects that we can link to. This may be a good place to also outline #58

### PR DESCRIPTION
**Pull request by adamltyson**
Closes #76

### CODE REVIEW

**Comment by adamltyson** [comment]
Should also add:
- Steve Lenzi collaboration on SpikeInterface
- Collab on RC2

**Review by alessandrofelder — APPROVED** [review]

**Comment by alessandrofelder** [comment]
I am happy with the parts I contribute to, but will hold off merging so others can check their parts.

**Review by lochhh — APPROVED** [review]

**Review by niksirbi — APPROVED** [review]
I'm fine with the content. My only comment is about the presentation. Should we add a 6th card - "Collaborations" on the homepage? It will make these projects more discoverable and will plug a hone in our card grid.

There's already an image for that card in _static btw, though I'm not particularly proud of it.

**Comment by adamltyson** [comment]
@niksirbi I've added that back in. It's not perfect, but I think it's nice. 6 cards make the homepage look nicer too.

**Comment by adamltyson** [comment]
Going to merge this following 3 approvals. If anyone else notices a mistake, please let me know.

**Pull request merged**
